version: '3.8'

services:
  api:
    build: .
    container_name: currency-converter-api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY:-demo_key}
      - REDIS_HOST=redis
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: currency-converter-ui
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app/streamlit_app
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: currency-converter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
